device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_alpha + BLK_ID * BLK_SZ, alpha, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_alpha + BLK_ID * BLK_SZ, alpha, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_alpha + BLK_ID * BLK_SZ, alpha, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_alpha + BLK_ID * BLK_SZ, deriv_evars->grad_0_alpha + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_chi + BLK_ID * BLK_SZ, chi, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_chi + BLK_ID * BLK_SZ, chi, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_chi + BLK_ID * BLK_SZ, chi, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_chi + BLK_ID * BLK_SZ, deriv_evars->grad_0_chi + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_K + BLK_ID * BLK_SZ, K, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_K + BLK_ID * BLK_SZ, K, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_Gt0 + BLK_ID * BLK_SZ, Gt0, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_Gt0 + BLK_ID * BLK_SZ, Gt0, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_Gt1 + BLK_ID * BLK_SZ, Gt1, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_Gt1 + BLK_ID * BLK_SZ, Gt1, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_Gt2 + BLK_ID * BLK_SZ, Gt2, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_Gt2 + BLK_ID * BLK_SZ, Gt2, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_beta0 + BLK_ID * BLK_SZ, beta0, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_beta0 + BLK_ID * BLK_SZ, beta0, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_beta0 + BLK_ID * BLK_SZ, beta0, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_beta0 + BLK_ID * BLK_SZ, deriv_evars->grad_0_beta0 + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_beta1 + BLK_ID * BLK_SZ, beta1, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_beta1 + BLK_ID * BLK_SZ, beta1, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_beta1 + BLK_ID * BLK_SZ, beta1, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_beta1 + BLK_ID * BLK_SZ, deriv_evars->grad_0_beta1 + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_beta2 + BLK_ID * BLK_SZ, beta2, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_beta2 + BLK_ID * BLK_SZ, beta2, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_beta2 + BLK_ID * BLK_SZ, beta2, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_beta2 + BLK_ID * BLK_SZ, deriv_evars->grad_0_beta2 + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_B0 + BLK_ID * BLK_SZ, B0, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_B0 + BLK_ID * BLK_SZ, B0, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_B1 + BLK_ID * BLK_SZ, B1, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_B1 + BLK_ID * BLK_SZ, B1, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_B2 + BLK_ID * BLK_SZ, B2, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_B2 + BLK_ID * BLK_SZ, B2, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_gt0 + BLK_ID * BLK_SZ, gt0, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt0 + BLK_ID * BLK_SZ, gt0, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt0 + BLK_ID * BLK_SZ, gt0, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt0 + BLK_ID * BLK_SZ, deriv_evars->grad_0_gt0 + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_gt1 + BLK_ID * BLK_SZ, gt1, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt1 + BLK_ID * BLK_SZ, gt1, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt1 + BLK_ID * BLK_SZ, gt1, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt1 + BLK_ID * BLK_SZ, deriv_evars->grad_0_gt1 + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_gt2 + BLK_ID * BLK_SZ, gt2, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt2 + BLK_ID * BLK_SZ, gt2, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt2 + BLK_ID * BLK_SZ, gt2, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt2 + BLK_ID * BLK_SZ, deriv_evars->grad_0_gt2 + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_gt3 + BLK_ID * BLK_SZ, gt3, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt3 + BLK_ID * BLK_SZ, gt3, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt3 + BLK_ID * BLK_SZ, gt3, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt3 + BLK_ID * BLK_SZ, deriv_evars->grad_0_gt3 + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_gt4 + BLK_ID * BLK_SZ, gt4, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt4 + BLK_ID * BLK_SZ, gt4, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt4 + BLK_ID * BLK_SZ, gt4, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt4 + BLK_ID * BLK_SZ, deriv_evars->grad_0_gt4 + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_gt5 + BLK_ID * BLK_SZ, gt5, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt5 + BLK_ID * BLK_SZ, gt5, blk + BLK_ID );
device::__deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt5 + BLK_ID * BLK_SZ, gt5, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt5 + BLK_ID * BLK_SZ, deriv_evars->grad_0_gt5 + BLK_ID * BLK_SZ, blk + BLK_ID);
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At0 + BLK_ID * BLK_SZ, At0, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At0 + BLK_ID * BLK_SZ, At0, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At1 + BLK_ID * BLK_SZ, At1, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At1 + BLK_ID * BLK_SZ, At1, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At2 + BLK_ID * BLK_SZ, At2, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At2 + BLK_ID * BLK_SZ, At2, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At3 + BLK_ID * BLK_SZ, At3, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At3 + BLK_ID * BLK_SZ, At3, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At4 + BLK_ID * BLK_SZ, At4, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At4 + BLK_ID * BLK_SZ, At4, blk + BLK_ID );
device::__deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At5 + BLK_ID * BLK_SZ, At5, blk + BLK_ID );
device::__ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At5 + BLK_ID * BLK_SZ, At5, blk + BLK_ID );
