__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , alpha, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_alpha + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_alpha + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_alpha + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_alpha + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_alpha + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_alpha + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_alpha + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_alpha + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_alpha + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_alpha + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_alpha + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_alpha + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , chi, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_chi + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_chi + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_chi + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_chi + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_chi + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_chi + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_chi + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_chi + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_chi + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_chi + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_chi + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_chi + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , K, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_K + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_K + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_K + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_K + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_K + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_K + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , Gt0, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_Gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_Gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_Gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_Gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_Gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_Gt0 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , Gt1, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_Gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_Gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_Gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_Gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_Gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_Gt1 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , Gt2, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_Gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_Gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_Gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_Gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_Gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_Gt2 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , beta0, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_beta0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_beta0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_beta0 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_beta0 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_beta0 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_beta0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_beta0 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_beta0 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_beta0 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_beta0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_beta0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_beta0 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , beta1, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_beta1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_beta1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_beta1 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_beta1 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_beta1 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_beta1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_beta1 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_beta1 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_beta1 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_beta1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_beta1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_beta1 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , beta2, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_beta2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_beta2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_beta2 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_beta2 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_beta2 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_beta2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_beta2 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_beta2 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_beta2 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_beta2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_beta2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_beta2 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , B0, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_B0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_B0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_B0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_B0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_B0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_B0 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , B1, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_B1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_B1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_B1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_B1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_B1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_B1 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , B2, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_B2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_B2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_B2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_B2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_B2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_B2 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt0, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_gt0 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt0 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_gt0 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt0 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_gt0 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_gt0 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_gt0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_gt0 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt1, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_gt1 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt1 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_gt1 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt1 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_gt1 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_gt1 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_gt1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_gt1 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt2, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_gt2 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt2 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_gt2 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt2 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_gt2 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_gt2 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_gt2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_gt2 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt3, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_gt3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_gt3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_gt3 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt3 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_gt3 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt3 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_gt3 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_gt3 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_gt3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_gt3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_gt3 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt4, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_gt4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_gt4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_gt4 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt4 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_gt4 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt4 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_gt4 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_gt4 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_gt4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_gt4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_gt4 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt5, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(deriv_evars->grad2_0_0_gt5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_gt5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_0_gt5 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad2_0_1_gt5 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_0_2_gt5 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(deriv_evars->grad2_1_1_gt5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_gt5 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
device::__st_blk_var1__<DEVICE_REAL,pw,nx>   (Du , deriv_evars->grad_1_gt5 + Z_ID * BLK_SZ, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad2_1_2_gt5 + Z_ID * BLK_SZ , Du, blk);
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(deriv_evars->grad2_2_2_gt5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_gt5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_gt5 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At0, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_At0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_At0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_At0 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_At0 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At1, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_At1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_At1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_At1 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_At1 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At2, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_At2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_At2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_At2 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_At2 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At3, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_At3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_At3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_At3 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_At3 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At4, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_At4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_At4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_At4 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_At4 + Z_ID * BLK_SZ , su, blk);
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At5, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(deriv_evars->grad_0_At5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(deriv_evars->kograd_0_At5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(deriv_evars->grad_1_At5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(deriv_evars->kograd_1_At5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(deriv_evars->grad_2_At5 + Z_ID * BLK_SZ , su, blk);
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(deriv_evars->kograd_2_At5 + Z_ID * BLK_SZ , su, blk);
