device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , alpha, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_alpha=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_alpha=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_alpha=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_alpha=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_alpha=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_alpha=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_alpha=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_alpha=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_alpha=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_alpha=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_alpha=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_alpha=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , chi, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_chi=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_chi=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_chi=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_chi=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_chi=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_chi=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_chi=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_chi=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_chi=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_chi=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_chi=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_chi=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , K, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_K=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_K=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_K=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_K=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_K=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_K=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , Gt0, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_Gt0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_Gt0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_Gt0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_Gt0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_Gt0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_Gt0=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , Gt1, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_Gt1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_Gt1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_Gt1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_Gt1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_Gt1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_Gt1=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , Gt2, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_Gt2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_Gt2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_Gt2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_Gt2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_Gt2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_Gt2=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , beta0, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_beta0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_beta0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_beta0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_beta0=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_beta0=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_beta0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_beta0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_beta0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_beta0=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_beta0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_beta0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_beta0=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , beta1, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_beta1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_beta1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_beta1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_beta1=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_beta1=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_beta1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_beta1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_beta1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_beta1=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_beta1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_beta1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_beta1=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , beta2, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_beta2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_beta2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_beta2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_beta2=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_beta2=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_beta2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_beta2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_beta2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_beta2=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_beta2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_beta2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_beta2=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , B0, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_B0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_B0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_B0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_B0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_B0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_B0=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , B1, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_B1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_B1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_B1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_B1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_B1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_B1=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , B2, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_B2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_B2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_B2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_B2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_B2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_B2=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt0, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_gt0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_gt0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_gt0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_gt0=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_gt0=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_gt0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_gt0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_gt0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_gt0=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_gt0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_gt0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_gt0=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt1, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_gt1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_gt1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_gt1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_gt1=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_gt1=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_gt1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_gt1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_gt1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_gt1=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_gt1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_gt1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_gt1=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt2, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_gt2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_gt2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_gt2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_gt2=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_gt2=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_gt2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_gt2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_gt2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_gt2=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_gt2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_gt2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_gt2=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt3, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_gt3=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_gt3=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_gt3=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_gt3=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_gt3=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_gt3=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_gt3=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_gt3=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_gt3=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_gt3=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_gt3=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_gt3=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt4, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_gt4=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_gt4=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_gt4=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_gt4=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_gt4=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_gt4=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_gt4=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_gt4=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_gt4=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_gt4=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_gt4=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_gt4=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , gt5, blk);
device::__blk1_deriv644_xx<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_0_0_gt5=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_gt5=Du[gidx];
__syncthreads();
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_gt5=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_1_gt5=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_0_2_gt5=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_yy<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_1_1_gt5=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_gt5=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_gt5=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(DDu , Du, blk);
__syncthreads();
const DEVICE_REAL grad2_1_2_gt5=DDu[gidx];
__syncthreads();
device::__blk1_deriv644_zz<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad2_2_2_gt5=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_gt5=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_gt5=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At0, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_At0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_At0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_At0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_At0=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_At0=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_At0=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At1, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_At1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_At1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_At1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_At1=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_At1=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_At1=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At2, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_At2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_At2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_At2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_At2=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_At2=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_At2=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At3, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_At3=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_At3=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_At3=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_At3=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_At3=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_At3=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At4, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_At4=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_At4=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_At4=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_At4=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_At4=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_At4=Du[gidx];
__syncthreads();
device::__ld_blk_var1__<DEVICE_REAL,pw,nx>   (su , At5, blk);
device::__blk1_deriv644_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_0_At5=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_x<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_0_At5=Du[gidx];
__syncthreads();
device::__blk1_deriv644_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_1_At5=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_y<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_1_At5=Du[gidx];
__syncthreads();
device::__blk1_deriv644_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL grad_2_At5=Du[gidx];
__syncthreads();
device::__blk1_ko_deriv42_z<pw,pencils,pencil_sz>(Du , su, blk);
__syncthreads();
const DEVICE_REAL kograd_2_At5=Du[gidx];
__syncthreads();
